export const GET_BOOK = "GET_BOOK"
export const GET_BOOK_REQUEST = "GET_BOOK_REQUEST"
export const GET_BOOK_SINLGE = "GET_BOOK_SINLGE"
export const ADD_BOOK = "ADD_BOOK"
export const DELETE_BOOK= "DELETE_BOOK"
export const UPDATE_BOOK = "UPDATE_BOOK"